language: node_js

node_js: 10

script: |
  ./build.sh

before_deploy: |
  export TRAVIS_TAG="$(jq -j '.version' < ./src/package.json)"

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: release
  script: |
    cd build/npm
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    npm publish --access public

    # tag commit
    git tag "${TRAVIS_TAG}"

    # push tag
    git remote add origin-tagging https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    git push origin-tagging "${TRAVIS_TAG}"
